#!/bin/sh
#
# An example hook script to verify what is about to be committed. Called by "gi$
# appropriate message if it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if which xdg-open > /dev/null 
then
  xdg-open "www.google.com.br" 
elif which gnome-open > /dev/null 
then
  gnome-open "ww.google.com.br"
fi

